import type { BaseEnv, BootstrapEnv, GeneratedEnv } from '../env.js';
import type { StripeProvisionResult } from '../providers/stripe.js';

export interface GenerateFilesResult {
  generatedEnvContents: string;
  devVarsContents: string;
}

export interface GenerateFilesOptions {
  base: BaseEnv;
  generated: GeneratedEnv;
  stripeResult?: StripeProvisionResult;
}

const GENERATED_ENV_HEADER = [
  '# Autogenerated by bootstrap CLI',
  '# Do not edit manually – rerun `pnpm bootstrap:env` instead.',
  ''
].join('\n');

const DEV_VARS_HEADER = [
  '# Autogenerated by bootstrap CLI',
  '# Keep secrets here for local wrangler dev; do not commit real production secrets.',
  ''
].join('\n');

export function buildGeneratedFiles(options: GenerateFilesOptions): GenerateFilesResult {
  const { base, generated, stripeResult } = options;
  const env: BootstrapEnv = {
    ...base,
    ...generated
  };

  const webEntries: Array<[string, string]> = [];
  const workerEntries: Array<[string, string]> = [];

  pushWeb(webEntries, 'PROJECT_ID', env.PROJECT_ID);
  pushWeb(webEntries, 'PROJECT_DOMAIN', env.PROJECT_DOMAIN ?? '');
  const projectHost = deriveProjectHost(env.PROJECT_DOMAIN);
  const appUrl = deriveAppUrl(env);
  const appBaseUrl = deriveAppBaseUrl(env);
  pushWeb(webEntries, 'PROJECT_HOST', projectHost);
  pushWeb(webEntries, 'APP_URL', appUrl);
  pushWeb(webEntries, 'APP_BASE_URL', appBaseUrl);

  const canonicalOrigin = deriveCanonicalOrigin(env);
  const workerOrigin = deriveWorkerOrigin(env, appUrl);
  const localOrigin = deriveLocalOrigin(env);

  // Better Auth configuration
  const betterAuthUrl = env.BETTER_AUTH_URL ?? `${canonicalOrigin}/api/auth`;
  const loginOrigin = env.LOGIN_ORIGIN ?? canonicalOrigin;
  const sessionCookieDomain = env.SESSION_COOKIE_DOMAIN ?? deriveProjectHost(env.PROJECT_DOMAIN);

  pushWeb(webEntries, 'BETTER_AUTH_URL', betterAuthUrl);
  pushWeb(webEntries, 'LOGIN_ORIGIN', loginOrigin);
  pushWeb(webEntries, 'SESSION_COOKIE_DOMAIN', sessionCookieDomain);
  pushWeb(webEntries, 'EXPO_PUBLIC_WORKER_ORIGIN', workerOrigin);
  pushWeb(webEntries, 'EXPO_PUBLIC_WORKER_ORIGIN_LOCAL', localOrigin);

  const d1Name = env.CLOUDFLARE_D1_NAME ?? `${env.PROJECT_ID}-d1`;
  const d1Id = env.D1_DATABASE_ID ?? env.CLOUDFLARE_D1_ID ?? '';
  const r2Bucket = env.CLOUDFLARE_R2_BUCKET ?? `${env.PROJECT_ID}-assets`;
  pushWeb(webEntries, 'CLOUDFLARE_D1_NAME', d1Name);
  pushWeb(webEntries, 'CLOUDFLARE_D1_ID', env.CLOUDFLARE_D1_ID ?? '');
  pushWeb(webEntries, 'D1_DATABASE_NAME', d1Name);
  pushWeb(webEntries, 'D1_DATABASE_ID', d1Id);
  pushWeb(webEntries, 'CLOUDFLARE_R2_BUCKET', r2Bucket);
  pushWeb(webEntries, 'R2_BUCKET_NAME', r2Bucket);
  pushWeb(webEntries, 'CLOUDFLARE_ZONE_ID', env.CLOUDFLARE_ZONE_ID ?? '');

  // Use Stripe result if available, otherwise fall back to env
  const stripeWebhookSecret =
    stripeResult?.webhook?.webhookSecret ?? env.STRIPE_WEBHOOK_SECRET ?? '';
  const stripeProductIds = stripeResult?.products
    ? stripeResult.products.map((p) => p.productId).join(',')
    : env.STRIPE_PRODUCT_IDS ?? '';
  const stripePriceIds = stripeResult?.products
    ? stripeResult.products.flatMap((p) => p.priceIds).join(',')
    : env.STRIPE_PRICE_IDS ?? '';
  const stripeWebhookUrl = stripeResult?.webhook?.webhookUrl ?? env.STRIPE_WEBHOOK_URL ?? '';

  pushWeb(webEntries, 'STRIPE_WEBHOOK_SECRET', stripeWebhookSecret);
  pushWeb(webEntries, 'STRIPE_WEBHOOK_URL', stripeWebhookUrl);
  pushWeb(webEntries, 'STRIPE_PRODUCT_DEFINITIONS', env.STRIPE_PRODUCT_DEFINITIONS ?? '');
  pushWeb(webEntries, 'STRIPE_PRODUCT_IDS', stripeProductIds);
  pushWeb(webEntries, 'STRIPE_PRICE_IDS', stripePriceIds);
  pushWeb(webEntries, 'STRIPE_PRODUCTS', env.STRIPE_PRODUCTS ?? '');

  // Worker-specific Better Auth variables
  pushWorker(workerEntries, 'BETTER_AUTH_URL', betterAuthUrl);
  pushWorker(workerEntries, 'LOGIN_ORIGIN', loginOrigin);
  pushWorker(workerEntries, 'SESSION_COOKIE_DOMAIN', sessionCookieDomain);
  pushWorker(workerEntries, 'CLOUDFLARE_R2_BUCKET', r2Bucket);
  pushWorker(workerEntries, 'STRIPE_SECRET_KEY', env.STRIPE_SECRET_KEY);
  pushWorker(workerEntries, 'STRIPE_WEBHOOK_SECRET', stripeWebhookSecret);

  const generatedEnvContents = GENERATED_ENV_HEADER + formatKeyValueBlock(webEntries);
  const devVarsContents = DEV_VARS_HEADER + formatKeyValueBlock(workerEntries);

  return {
    generatedEnvContents,
    devVarsContents
  };
}

function pushWeb(target: Array<[string, string]>, key: string, value?: string): void {
  target.push([key, value ?? '']);
}

function pushWorker(target: Array<[string, string]>, key: string, value?: string): void {
  target.push([key, value ?? '']);
}

function formatKeyValueBlock(entries: Array<[string, string]>): string {
  return entries
    .map(([key, value]) => `${key}=${escapeValue(value)}`)
    .join('\n');
}

function escapeValue(value: string): string {
  if (value === '') return '';
  if (/^[A-Za-z0-9_./:-]+$/.test(value)) {
    return value;
  }
  if (!value.includes("'")) {
    return `'${value}'`;
  }
  return JSON.stringify(value);
}

function deriveProjectHost(domain?: string): string {
  if (!domain) return '';
  const withoutScheme = domain.replace(/^https?:\/\//, '');
  return withoutScheme.split('/')[0].split(':')[0];
}

function deriveAppBaseUrl(env: BootstrapEnv): string {
  return env.APP_BASE_URL ?? '/app';
}

export function deriveAppUrl(env: BootstrapEnv): string {
  if (env.APP_URL) return env.APP_URL;
  if (env.PROJECT_DOMAIN) {
    const trimmed = trimTrailingSlash(env.PROJECT_DOMAIN);
    return `${trimmed}${deriveAppBaseUrl(env)}`;
  }
  return '/app';
}

export function deriveWorkerOrigin(env: BootstrapEnv, resolvedAppUrl: string): string {
  if (env.WORKER_ORIGIN) return env.WORKER_ORIGIN;
  if (resolvedAppUrl) return originFromUrl(resolvedAppUrl);
  if (env.PROJECT_DOMAIN) return originFromUrl(env.PROJECT_DOMAIN);
  return '';
}

function deriveCanonicalOrigin(env: BootstrapEnv): string {
  if (env.PROJECT_DOMAIN) {
    return originFromUrl(env.PROJECT_DOMAIN);
  }
  return `https://${env.PROJECT_ID}.justevery.com`;
}

function deriveLocalOrigin(env: BootstrapEnv): string {
  const candidate = env.EXPO_PUBLIC_WORKER_ORIGIN_LOCAL ?? 'http://127.0.0.1:8787';
  const normalised = originFromUrl(candidate);
  return normalised || 'http://127.0.0.1:8787';
}

function originFromUrl(url: string): string {
  const trimmed = trimTrailingSlash(url);
  if (!/^https?:/i.test(trimmed)) {
    return trimmed;
  }
  try {
    const parsed = new URL(trimmed);
    return `${parsed.protocol}//${parsed.host}`;
  } catch {
    return trimmed;
  }
}

function trimTrailingSlash(value: string): string {
  return value.replace(/\/$/, '');
}
