# shellcheck shell=bash

ensure_worker_secret() {
  local name=$1
  local value=$2

  if [[ -z "$value" ]]; then
    log_warn "Worker secret '$name' is empty; skipping"
    return
  fi

  if [[ "${SYNC_SECRETS:-1}" == "0" ]]; then
    log_info "Secret sync disabled (SYNC_SECRETS=0); skipping $name"
    return
  fi

  log_info "Syncing Worker secret $name"

  if is_dry_run; then
    log_info "[dry-run] ${WRANGLER_LABEL} secret put ${name}"
    return
  fi

  local output=""
  if output=$(printf '%s' "$value" | "${WRANGLER_BASE[@]}" secret put "$name" 2>&1); then
    return
  fi

  if [[ "$output" == *"Binding name '${name}' already in use"* ]]; then
    log_info "Worker secret $name already present; leaving as-is"
  else
    log_warn "Failed to sync Worker secret $name: $output"
  fi
}

sync_worker_secrets() {
  ensure_worker_secret LOGTO_APPLICATION_ID "${LOGTO_APPLICATION_ID:-}"
  ensure_worker_secret STRIPE_SECRET_KEY "${STRIPE_SECRET_KEY:-}"
  ensure_worker_secret STRIPE_WEBHOOK_SECRET "${STRIPE_WEBHOOK_SECRET:-}"
}

deploy_worker() {
  if is_dry_run; then
    log_info "[dry-run] Would deploy Worker via ${WRANGLER_LABEL} deploy"
    return
  fi
  log_info "Deploying Worker via ${WRANGLER_LABEL} deploy"
  wrangler_cmd deploy
}

write_generated_env() {
  if is_dry_run; then
    log_info "[dry-run] Would write $GENERATED_ENV_FILE"
    return
  fi

  log_info "Writing ${GENERATED_ENV_FILE#$ROOT_DIR/}"
  {
    printf '# Autogenerated by bootstrap.sh on %s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    printf '# Do not edit manually – rerun bootstrap.sh instead.\n\n'
    printf 'PROJECT_ID=%s\n' "${PROJECT_ID:-}"
    printf 'PROJECT_DOMAIN=%s\n' "${PROJECT_DOMAIN:-}"
    printf 'APP_URL=%s\n' "${APP_URL:-}"
    printf 'APP_BASE_URL=%s\n' "${APP_BASE_URL:-}"
    printf 'LOGTO_ENDPOINT=%s\n' "${LOGTO_ENDPOINT:-}"
    printf 'LOGTO_APPLICATION_ID=%s\n' "${LOGTO_APPLICATION_ID:-}"
    printf 'LOGTO_ISSUER=%s\n' "${LOGTO_ISSUER:-}"
    printf 'LOGTO_JWKS_URI=%s\n' "${LOGTO_JWKS_URI:-}"
    printf 'LOGTO_API_RESOURCE=%s\n' "${LOGTO_API_RESOURCE:-}"
    printf 'EXPO_PUBLIC_LOGTO_ENDPOINT=%s\n' "${EXPO_PUBLIC_LOGTO_ENDPOINT:-}"
    printf 'EXPO_PUBLIC_LOGTO_APP_ID=%s\n' "${EXPO_PUBLIC_LOGTO_APP_ID:-}"
    printf 'EXPO_PUBLIC_API_RESOURCE=%s\n' "${EXPO_PUBLIC_API_RESOURCE:-}"
    printf 'EXPO_PUBLIC_LOGTO_REDIRECT_URI=%s\n' "${EXPO_PUBLIC_LOGTO_REDIRECT_URI:-}"
    printf 'EXPO_PUBLIC_LOGTO_SCOPES=%s\n' "${EXPO_PUBLIC_LOGTO_SCOPES:-}"
    printf 'EXPO_PUBLIC_LOGTO_RESOURCES=%s\n' "${EXPO_PUBLIC_LOGTO_RESOURCES:-}"
    printf 'EXPO_PUBLIC_LOGTO_POST_LOGOUT_REDIRECT_URI=%s\n' "${EXPO_PUBLIC_LOGTO_POST_LOGOUT_REDIRECT_URI:-}"
    printf 'EXPO_PUBLIC_WORKER_ORIGIN=%s\n' "${EXPO_PUBLIC_WORKER_ORIGIN:-}"
    printf 'D1_DATABASE_NAME=%s\n' "${D1_DATABASE_NAME:-}"
    printf 'D1_DATABASE_ID=%s\n' "${D1_DATABASE_ID:-}"
    printf 'R2_BUCKET_NAME=%s\n' "${R2_BUCKET_NAME:-}"
    printf 'CLOUDFLARE_ZONE_ID=%s\n' "${CLOUDFLARE_ZONE_ID:-}"
    printf 'STRIPE_PRODUCT_IDS="%s"\n' "${STRIPE_PRODUCT_IDS:-[]}"
    printf 'STRIPE_WEBHOOK_ENDPOINT_ID=%s\n' "${STRIPE_WEBHOOK_ENDPOINT_ID:-}"
    printf 'STRIPE_WEBHOOK_SECRET=%s\n' "${STRIPE_WEBHOOK_SECRET:-}"
    printf 'STRIPE_MODE=%s\n' "${STRIPE_MODE:-}"
    printf 'STRIPE_SECRET_SOURCE=%s\n' "${STRIPE_SECRET_SOURCE:-}"
  } >"$GENERATED_ENV_FILE"
}

post_deploy_guidance() {
  logto_post_deploy_note
  stripe_post_deploy_note
}
