# shellcheck shell=bash

ensure_worker_secret() {
  local name=$1
  local value=$2

  if [[ -z "$value" ]]; then
    log_warn "Worker secret '$name' is empty; skipping"
    return
  fi

  if [[ "${BOOTSTRAP_DEPLOY:-0}" != "1" ]]; then
    log_info "Local mode: skipping Worker secret '$name'"
    return
  fi

  log_info "Syncing Worker secret $name"

  local output=""
  if output=$(printf '%s' "$value" | "${WRANGLER_BASE[@]}" secret put "$name" 2>&1); then
    return
  fi

  if [[ "$output" == *"Binding name '${name}' already in use"* ]]; then
    log_info "Worker secret $name already present; leaving as-is"
  else
    log_warn "Failed to sync Worker secret $name: $output"
  fi
}

sync_worker_secrets() {
  ensure_worker_secret LOGTO_APPLICATION_ID "${LOGTO_APPLICATION_ID:-}"
  ensure_worker_secret STRIPE_SECRET_KEY "${STRIPE_SECRET_KEY:-}"
  ensure_worker_secret STRIPE_WEBHOOK_SECRET "${STRIPE_WEBHOOK_SECRET:-}"
}

deploy_worker() {
  log_info "Deploying Worker via ${WRANGLER_LABEL} deploy"
  wrangler_cmd deploy
}

write_generated_env() {
  log_info "Writing ${GENERATED_ENV_FILE#$ROOT_DIR/}"
  {
    printf '# Autogenerated by bootstrap.sh on %s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    printf '# Do not edit manually – rerun bootstrap.sh instead.\n\n'
    print_env_line 'PROJECT_ID' "${PROJECT_ID:-}"
    print_env_line 'PROJECT_DOMAIN' "${PROJECT_DOMAIN:-}"
    print_env_line 'APP_URL' "${APP_URL:-}"
    print_env_line 'APP_BASE_URL' "${APP_BASE_URL:-}"
    print_env_line 'LOGTO_ENDPOINT' "${LOGTO_ENDPOINT:-}"
    print_env_line 'LOGTO_APPLICATION_ID' "${LOGTO_APPLICATION_ID:-}"
    print_env_line 'LOGTO_ISSUER' "${LOGTO_ISSUER:-}"
    print_env_line 'LOGTO_JWKS_URI' "${LOGTO_JWKS_URI:-}"
    print_env_line 'LOGTO_API_RESOURCE' "${LOGTO_API_RESOURCE:-}"
    print_env_line 'LOGTO_API_RESOURCE_ID' "${LOGTO_API_RESOURCE_ID:-}"
    print_env_line 'EXPO_PUBLIC_LOGTO_ENDPOINT' "${EXPO_PUBLIC_LOGTO_ENDPOINT:-}"
    print_env_line 'EXPO_PUBLIC_LOGTO_APP_ID' "${EXPO_PUBLIC_LOGTO_APP_ID:-}"
    print_env_line 'EXPO_PUBLIC_API_RESOURCE' "${EXPO_PUBLIC_API_RESOURCE:-}"
    print_env_line 'EXPO_PUBLIC_LOGTO_REDIRECT_URI' "${EXPO_PUBLIC_LOGTO_REDIRECT_URI:-}"
    print_env_line 'EXPO_PUBLIC_LOGTO_REDIRECT_URI_LOCAL' "${EXPO_PUBLIC_LOGTO_REDIRECT_URI_LOCAL:-}"
    print_env_line 'EXPO_PUBLIC_LOGTO_REDIRECT_URI_PROD' "${EXPO_PUBLIC_LOGTO_REDIRECT_URI_PROD:-}"
    print_env_line 'EXPO_PUBLIC_LOGTO_SCOPES' "${EXPO_PUBLIC_LOGTO_SCOPES:-}"
    print_env_line 'EXPO_PUBLIC_LOGTO_RESOURCES' "${EXPO_PUBLIC_LOGTO_RESOURCES:-}"
    print_env_line 'EXPO_PUBLIC_LOGTO_POST_LOGOUT_REDIRECT_URI' "${EXPO_PUBLIC_LOGTO_POST_LOGOUT_REDIRECT_URI:-}"
    print_env_line 'EXPO_PUBLIC_WORKER_ORIGIN' "${EXPO_PUBLIC_WORKER_ORIGIN:-}"
    print_env_line 'EXPO_PUBLIC_WORKER_ORIGIN_LOCAL' "${EXPO_PUBLIC_WORKER_ORIGIN_LOCAL:-}"
    print_env_line 'D1_DATABASE_NAME' "${D1_DATABASE_NAME:-}"
    print_env_line 'D1_DATABASE_ID' "${D1_DATABASE_ID:-}"
    print_env_line 'R2_BUCKET_NAME' "${R2_BUCKET_NAME:-}"
    print_env_line 'CLOUDFLARE_ZONE_ID' "${CLOUDFLARE_ZONE_ID:-}"
    print_env_line 'STRIPE_PRODUCT_IDS' "${STRIPE_PRODUCT_IDS:-[]}"
    print_env_line 'STRIPE_WEBHOOK_ENDPOINT_ID' "${STRIPE_WEBHOOK_ENDPOINT_ID:-}"
    print_env_line 'STRIPE_WEBHOOK_SECRET' "${STRIPE_WEBHOOK_SECRET:-}"
    print_env_line 'STRIPE_MODE' "${STRIPE_MODE:-}"
    print_env_line 'STRIPE_SECRET_SOURCE' "${STRIPE_SECRET_SOURCE:-}"
    print_env_line 'LOGTO_M2M_APP_NAME' "${LOGTO_M2M_APP_NAME:-}"
    print_env_line 'LOGTO_M2M_CLIENT_ID' "${LOGTO_M2M_CLIENT_ID:-}"
    print_env_line 'LOGTO_M2M_CLIENT_SECRET' "${LOGTO_M2M_CLIENT_SECRET:-}"
  } >"$GENERATED_ENV_FILE"
}

post_deploy_guidance() {
  logto_post_deploy_note
  stripe_post_deploy_note
}
